config: [config, default.yaml]
columns: [-1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1]
rows: [2, 3, 4, 5, 1, 2]
legends: [
  ["",        "\"\n'",  "W",      "F",      "P",      "B",    "J",      "L",      "U",      "Y",      "-\n\u2014",  ""],
  ["",        "A",      "R",      "S",      "T",      "G",    "M",      "N",      "E",      "I",      "O",          ""],
  ["",        "X",      "V",      "C",      "D",      "Q",    "Z",      "H",      "K",      ";\n,",   ":\n.",       ""],
  ["",        "",       "\u2318", "\u238B", "\u2388", "",     "",       "\u2325", "\u2326", "\u2261", "",           ""],
  ["",        "",       "",       "",       "\u21E4", "",     "",       "\u21E5", "",       "",       "",           ""],
  ["\u23CE",  "",       "",       "",       "\u2423", "#",    "\u25C7", "\u232B", "",       "",       "",           "\u21E7"]
  ]
require_legend: true