# Default Parameters for BD_Keyboard keycaps.
# ---- Alias definitions ----
legend_style_options:
  doubleshot: &doubleshot doubleshot
  engraved: &engraved engraved
  printed: &printed printed # Includes dye sublimation
spacing_options:
  mx: &spacing_mx [19, 19]
  mx_inch: &spacing_mx_inch [19.05, 19.05]
  choc: &spacing_choc [18, 17]
stem_options:
  mx: &stem_mx 0
  choc: &stem_choc 1
  mx_ribbed: &stem_mx_ribbed 2
  choc_ribbed: &stem_choc_ribbed 3
# ---- Keycap Parameters ----
# Clearance between keycaps.
clearance: 1
# Color of the keycap.
# color: "CornflowerBlue"
color: 0x663399 #RebeccaPurple
# Keycap size in spacing units.
dimensions: [1, 1]
# Label of the keycap when viewed in OCP_VSCode.
label: Keycap
# Keycap material for informational purposes.
material: PBT
# X- and Y- dimensions of the base of the keycap.
spacing: *spacing_choc
# Type of stem. See stem_types above for options.
stem_type: *stem_mx_ribbed
# Thickness of keycap shell.
thickness: 1.6
Legend:
  # Legend color.
  # color: 0x202020
  color: GhostWhite
  # Engraved legend depth.
  depth: 0.5
  # Legend font.
  font: Fira Code
  # Font style.
  font_style: regular
  # Position of legend on keycap.
  position: [0, 0]
  # Thickness of printed legend.
  print_thickness: 0.01
  # Size of legend (mm).
  size: 5
  # Legend style.
  style: *doubleshot
# The sides of the keycap that extend down from the top.
Skirt:
  # Angle of the bottom of the skirt.
  base_angle: 80
  # Radius of the corners at the bottom and top of the keycap.
  fillet_radii: [1, 2]
  # How far above the bottom of the skirt is relative to the bottom of the stem.
  height: 1
Top:
  # Angles about the X- and Y- axes of the top of the keycap.
  angles: [0, 0]
  # Amount that angles change between rows/columns.
  angle_increments: [2, 5]
  # Distance that top is offset from center of the base.
  offsets: [0, 0]
  # Amount that the offsets change between rows/columns.
  offset_increments: [1, 0.5]
  # Points used to define the spline forming the front-to-back curvature of the
  # keycap top. The second value defines the position of the point along the
  # Y-axis as a fraction of the top's Y size (immediately above). The third
  # defines the height of the point as a fraction of center height.
  center_points: [
    [0,   0.1,    1   ],
    [0,   0.17,   1.1 ],
    [0,   0,      1   ],
    [0,   0.17,   1.1 ],
    [0,   0.1,    1   ]
    ]
  center_point_references: [-1, -1, 0, 1, 1]
  # Tangent angles for the spline (see above).
  center_tangents: [30, 0, 0, 0, -30]
  # Angle of the side ridges.
  ridge_angle: 45
  # Height (sagitta) of side ridge.
  ridge_height: 1
  # Position of the side ridges relative to the keycap size.
  ridge_inset: 0.15
  #
  ridge_position_z: 1.2