config: [config, default.yaml]
columns: [-1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1]
rows: [2, 3, 4, 2]
legends: [
  ["\u21E5",  "Q",      "W",      "E",      "R",      "T",    "Y",      "U",      "I",      "O",      "P",      "\u232B"],
  ["\u238B",  "A",      "S",      "D",      "F",      "G",    "H",      "J",      "K",      "L",      ":\n;",   "\"\n'"],
  ["\u21E7",  "Z",      "X",      "C",      "V",      "B",    "N",      "M",      "<\n,",   ">\n.",   "?\n/",   "\u23CE"],
  ["\u25C7",  "\u2388", "\u2318", "\u2325", "\u21DF", " ",    " ",      "\u21DE", "\u2190", "\u2193", "\u2191", "\u2192"],
  ]
require_legend: true