[project]
name = "bd_keyboard"
version = "0.0.1"
authors = [
  { name="Joshua Lucas", email="joshdlucas@gmail.com" },
]
description = "Build123d library of keyboard components."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "bd_warehouse",
  "build123d>=0.10.0",
  "dataclass_wizard",
  "ocp_vscode"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "LicenseRef-Apache-2.0"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Silcantar/bd_keyboard"
Issues = "https://github.com/Silcantar/bd_keyboard/issues"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false