# Parameters for BD_Keyboard keycaps.
# Alias definitions
thickness: &thickness 1
stem_types:
  mx: &mx 0
  choc: &choc 1
  mx_ribbed: &mx_ribbed 2
  choc_ribbed: &choc_ribbed 3
# Keycap Parameters
# Color of the keycap.
color: "CornflowerBlue"
# Z-position of the center of the top dish.
height: 6
# Label of the keycap when viewed in OCP_VSCode.
label: Keycap
# Keycap material for informational purposes.
material: PBT
# X- and Y- dimensions of the base of the keycap.
size: [18, 18]
# Type of stem. See stem_types above for options.
stem_type: *mx
# The sides of the keycap that extend down from the top.
Skirt:
  # Fillet of the inside and outside bottom edges of the skirt.
  bottom_fillet_radius: 0.3
  # Radius of the corners at the bottom and top of the keycap.
  fillet_radii: [2, 6]
  # How far above the bottom of the skirt is relative to the bottom of the stem.
  height: 1
  # Thickness of the keycap sides.
  thickness: *thickness
Top:
  # Angles about the X- and Y- axes of the top of the keycap.
  angles: [0, 0]
  # Radius of the left-right (about the Y-axis) curvature of the keycap top.
  dish_radius: 30
  # Radius of the top edges of the keycap.
  fillet_radius: 1
  # Radius of the top inside edge of the keycap.
  inside_fillet_radius: 0.5
  # Distance that the center of the top of the keycap is offset from the stem
  # in the X- and Y-directions.
  offset: [0, 0]
  # Dimensions of the top surface of the keycap in the X- and Y-directions.
  size: [14, 14]
  # Points used to define the spline forming the front-to-back curvature of the
  # keycap top. The first value defines the position of the point along the
  # Y-axis as a fraction of the top's Y size (immediately above). The second
  # defines the height of the point as a fraction of the top thickness (see
  # below.)
  spline_points: [
    [-0.5, 0.2],
    [-0.4, 0.3],
    [0, 0],
    [0.4, 0.3],
    [0.5, 0.2]
    ]
  # Tangent angles for the spline (see above).
  spline_tangents: [30, 0, 0, 0, -30]
  # Weight of each tangent.
  spline_scalars: [1, 1, 2, 1, 1]
  # Thickness of the keycap top.
  thickness: *thickness